# Generated by Django 4.0.2 on 2022-02-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('birth', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visited', models.DateTimeField(auto_now=True)),
                ('initials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.initials')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
